//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public long Id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string ProductModel { get; set; }
        public string Month { get; set; }
        public Nullable<long> Expense { get; set; }
    }
}
